name: Update packages that depends on ogc-api-processes-fastapi

on:
  workflow_dispatch:
  push:
    tags:
    - "v*"

jobs:
  update-downstream-packages:
    name: Pull request to update packages
    uses: ecmwf-projects/cads-build-farm/.github/workflows/update-downstream-packages.yaml@main
    with:
      package-ref: "OGC_API_PROCESSES_FASTAPI_REF"
      repositories: |
        ecmwf-projects/cads-processing-api-service
    secrets: inherit
